title: "Azure Bootcamp"
summary: "Azureã®åŸºæœ¬çš„ãªæ“ä½œã‚’è©¦ã—ã¦è¦šãˆã‚‹æœ¬"
topics: ["Azure", "VM"]
published: false
price: 0
# ğŸ‘‡ ã“ã“ã§ãƒãƒ£ãƒ—ã‚¿ãƒ¼ã®ä¸¦ã³é †ã‚’æŒ‡å®šã™ã‚‹
chapters:
  - about
  - vm-by-portal
  - vm-by-cli
  - blue-green-deploy-with-application-gateway
  
